### PR TITLE
test(MM-T4886): Update step 2 for existing test MM-T4886.md 

### PR DESCRIPTION
**Pull request by jgilliam17**
Correcting typo in step 2 of the test case. Changing `@` to `~`

#### Is the feature in stable branch or under review?
- [] Feature in stable branch (master, main)?
- [] Feature still under review? If yes, list all related pull requests for reference.

#### Test client

- [] Browser
- [] Mobile App (version, OS)
- [] Desktop App (version, OS)

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/14"></a>

### CODE REVIEW

**Comment by furqanmlk** [comment]
@jgilliam17 
I think you might need to change title too. 
You can use this PR for reference

https://github.com/mattermost/mattermost-test-management/pull/10

**Review by josephbaylon — APPROVED** [review]
LGTM. I believe Furqan has a suggestion on the title

**Comment by jgilliam17** [comment]
Thanks Joseph
Furqan - does that mean I need to remove lines 33 through 36?

**Comment by jgilliam17** [comment]
@furqanmlk updated. Let me know if this looks better. Thanks

**Review by saturninoabril — APPROVED** [review]
Thanks Jelena, looks like it's good. Maybe we could agree on PR title format for test case update. Could be like:
```
test(test key): update description
```

I'm merging this now.

**Pull request merged**
