### PR TITLE
chore: move priority_p1_to_p4 to require field

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Move priority_p1_to_p4 to require field.
See discussion https://github.com/mattermost/mattermost-test-management/pull/19#discussion_r1031741268

Main changes were at:
- src/util/markdown.ts
- - data/TEST_CASE_TEMPLATE.md
- README.md

Changes to data/test-cases/ were auto-generated.

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/26"></a>

### CODE REVIEW

**Review by yasserfaraazkhan — APPROVED** [review]
thank you @saturninoabril ,

just out of curiosity, does the isValidPriority in test_case.ts#295 will throw error is this files is empty?

**Comment by saturninoabril** [comment]
Currently, it will throw an error only if the value is not valid but will not throw an error if empty as it considers null value as valid value. It (null) is still included as possible value [here](https://github.com/mattermost/mattermost-test-management/blob/main/src/util/test_case.ts#L248-L254) since there are lots of test cases with `priority_p1_to_p4: null` (ex. [here](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/apps-framework/figma/MM-T5157.md?plain=1#L11)).

One option to make it throw an error is to assign those with null value to other value, like P3:
```diff
- priority_p1_to_p4: null
+ priority_p1_to_p4: "P3 - Deep Functions (Do extensive scenarios work?)"
```

@lindalumitchell Thoughts before I changed all to above value? Note that currently, there are 1,584 test cases without `priority_p1_to_p4` assigned yet.

**Review by furqanmlk — COMMENTED** [review]
Thanks @saturninoabril lot of work 👍 

Should we allow `null` if there is a default value ?

**Comment by saturninoabril** [comment]
Once we agree with the default value, ex. P3, and then apply it to all remaining 1,584 test cases, then we can remove the `null` as possible value.

**Review by lindalumitchell — APPROVED** [review]
@saturninoabril goodness, that's a lovely, giant amoung of cleaning up! I think it's a fine idea. Thank you!

**Comment by saturninoabril** [comment]
Thanks everyone!

@furqanmlk with the assignment of all from `null` to `P3...`, `null` as valid option has been removed on recent push. Please take a look again.

**Review by furqanmlk — APPROVED** [review]
Thanks @saturninoabril 
Truly appreciate to consider my suggestion. Excellent work.

**Pull request merged**
