### PR TITLE
chore(actions): user mattermost-quality as commit-author

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**

### CODE REVIEW

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Hello @yasserfaraazkhan, let me know if this is ready for review.

Also, do you know what were the change at `data/test-cases-toc.json`? I would expect no change there. Could you revert that file?
Screenshot 2023-03-16 at 4 29 45 PM

**Comment by yasserfaraazkhan** [comment]
> Hello @yasserfaraazkhan, let me know if this is ready for review.
> 
> Also, do you know what were the change at `data/test-cases-toc.json`? I would expect no change there. Could you revert that file? Screenshot 2023-03-16 at 4 29 45 PM

Hi @saturninoabril ,
this is up for review, the job ran successfully and pulled new Data-sync changes

**Comment by saturninoabril** [comment]
Thanks Yasser. However, I would expect that the save/sync will happen once merged to main only. Is it not the case?

Another that worries me is the changes happening at `data/test-cases-toc.json`. Can you take a look?

In this PR, I thought the related change is only at `.github/workflows/deno.yml` and other files should be reverted.

**Comment by yasserfaraazkhan** [comment]
> Thanks Yasser. However, I would expect that the save/sync will happen once merged to main only. Is it not the case?
> 
> Another that worries me is the changes happening at `data/test-cases-toc.json`. Can you take a look?
> 
> In this PR, I thought the related change is only at `.github/workflows/deno.yml` and other files should be reverted.

For testing purpose I run it on this branch to confirm sync is automatically, but from now on it will run post merge, I'll try to remove the sync changes.

the `data/test-cases-toc.json` was just new line getting added. I'll take a look once

**Comment by yasserfaraazkhan** [comment]
Hi @saturninoabril 
this should be good to get merged now 😄

**Review by saturninoabril — APPROVED** [review]
Thanks Yasser, LGTM!

**Comment by saturninoabril** [comment]
Btw, Eli is out and so I'm requesting review from Mario.

**Review by mvitale1989 — APPROVED** [review]
LGTM as well, thanks Yasser!

**Pull request merged**
