### PR TITLE
test(call from profile popover): New test case for starting a call from the profile popover

### PR DESCRIPTION
**Pull request by jgilliam17**
#### Summary

Created for community added Cypress test. See linked PR

#### Is the feature in stable branch or under review?
- [] Feature in stable branch (master, main)?
- [x] Feature still under review? If yes, list all related pull requests for reference.
https://github.com/mattermost/mattermost-webapp/pull/12080
#### Test server

https://mattermost-webapp-pr-12080.test.mattermost.cloud/
#### Test client

- [x] Browser
- [] Mobile App (version, OS)
- [x] Desktop App (version, OS)

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/63"></a>

### CODE REVIEW

**Comment by jgilliam17** [comment]
@josephbaylon I heard you mention Calls e2es in our meeting, so I added you here. Sinan has created one cypress test for Calls, here is the Zephyr equivalent

**Review by saturninoabril — APPROVED** [review]
Thanks Jelena, LGTM!

**Review by josephbaylon — APPROVED** [review]
LGTM

**Comment by saturninoabril** [comment]
@jgilliam17 Done save and sync - MM-T5382

**Pull request merged**
