### PR TITLE
test(MM-T4870): Update onboarding task list to reflect current design

### PR DESCRIPTION
**Pull request by stevemudie**
#### Summary
Text changes to reflect the current wording of the first admin onboarding task list.

See the tickets below for more details:
- [A/B Test: Reduce Onboarding Task List Items](https://mattermost.atlassian.net/browse/MM-47931)
- [Copy changes for Onboarding Task List](https://mattermost.atlassian.net/browse/MM-47242)

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/33"></a>

### CODE REVIEW

**Comment by stevemudie** [comment]
First admin oboarding task list

**Comment by stevemudie** [comment]
@saturninoabril How do we go about adding a new screenshot to the test case?

The current test case has [the older design](https://smartbear-tm4j-prod-us-west-2-attachment-rich-text.s3.us-west-2.amazonaws.com/embedded-f3277290f945470c4add5d21ef3dc7ca7b74388fc7152bfb6b99ae58c66a95a8-1655841009354-Screen+Shot+2022-06-21+at+3.50.06+PM.png) still and should be replaced with this one - or at the least removed once the changes are merged.

**Comment by jgilliam17** [comment]
That's a great point @stevemudie I can see the old one listed on the line 68. I am also curious to find out how to add new images.

**Comment by saturninoabril** [comment]
Hello @stevemudie, thanks for updating the test case!

Good question about the image. Will think about it in the future but a quick workaround would be:
1. Add the image at `data/asset/` folder (please create the folder).
2. Image file should have a format to easily reference. Suggested format would be `<test_key>-<short_description>.png`, ex. `MM-T4870-onboarding-task-list.png`.
3. Then in the markdown file, the syntax would be ``.

Example:
```markdown
![](https://raw.githubusercontent.com/mattermost/mattermost-test-management/main/data/asset/MM-T4870-onboarding-task-list.png)
```

fyi @lindalumitchell @lindy65, to be added to docs. TIA.

**Review by saturninoabril — CHANGES_REQUESTED** [review]
Please add the image in the new folder `data/asset` as suggested https://github.com/mattermost/mattermost-test-management/pull/33#issuecomment-1343812960. Then replace the old with new image link in the markdown file.

Thanks @stevemudie!

**Comment by saturninoabril** [comment]
Hello @stevemudie, let me know if you need help.

**Comment by stevemudie** [comment]
@saturninoabril I've added the link to the image directly but without the need for the subfolder. More details [here](https://community.mattermost.com/core/pl/95cowmczaf84uggppfgbz6nx9h).

Unfortunately, in the process it created a [new PR here](https://github.com/mattermost/mattermost-test-management/pull/49). Can we abandon this one and merge that one if it looks good?

**Comment by saturninoabril** [comment]
Hello Steve, sounds good to me. Closing now.

**Pull request closed without merging**
