### PR TITLE
chore: update validate function

### PR DESCRIPTION
**Pull request by yasserfaraazkhan**
- keep track of folder errors and return the boolean falue
- Throw error in Validate.ts, if any error found in the process

Reference PR
https://github.com/mattermost/mattermost-test-management/pull/24

### CODE REVIEW

**Comment by saturninoabril** [comment]
Sorry Yasser, I realized that we're already throwing an error [here whenever there's invalid test file/s](https://github.com/mattermost/mattermost-test-management/pull/27/files#diff-8c914c59188e7ca73d3152e502aff29fbaa7ec985eff316e4442585532f5d31cR216). With that I would suggest to move up the declaration of `invalidFiles` and push there the file and error from folder [here](https://github.com/mattermost/mattermost-test-management/pull/27/files#diff-8c914c59188e7ca73d3152e502aff29fbaa7ec985eff316e4442585532f5d31cR82) and [here](https://github.com/mattermost/mattermost-test-management/pull/27/files#diff-8c914c59188e7ca73d3152e502aff29fbaa7ec985eff316e4442585532f5d31cR98-R100).

**Comment by yasserfaraazkhan** [comment]
Ohh!! that's great @saturninoabril , 

I got a chance to explore the codebase 🙌 .

shall I close the PR, as its handled?

**Comment by saturninoabril** [comment]
Hello Yasser, sorry for the confusion. Throwing of error is not yet handled currently for folder. See suggestion - https://github.com/mattermost/mattermost-test-management/pull/27#issuecomment-1328538460

**Comment by yasserfaraazkhan** [comment]
the changes are working as expected. Will close this change and will keep an eye if anything comes up.

**Comment by saturninoabril** [comment]
I think not fully until we address as commented in https://github.com/mattermost/mattermost-test-management/pull/27#issuecomment-1328538460. I'll take a look.

**Pull request closed without merging**
